config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users, only: [:show]
     
  namespace :manager do
    resources :clients do 
      resources :projects do 
        resources :comments
      end
    end

    resources :payments
    
  end 

  namespace :admin do
    resources :users do
      member do 
        get :enable
        get :disable
      end
    end
  end


  root "manager/clients#index"

end

app/models/client.rb
class Client < ApplicationRecord

  has_many :projects
  has_many :comments
  has_many :payments

  validates :name, :address, :profession, presence: true
  validates :contact, presence: true, numericality: true
  validates :email, presence: true, format: { with: Devise.email_regexp, on: :create }, uniqueness: { case_sensitive: false }
  
end

app/controllers/manager/base_controller.rb
module Manager
  class BaseController < ApplicationController
    before_action :validate_admin_or_manager

    def validate_admin_or_manager

      # if !(current_user.admin? || current_user.manager?)
      #   flash[:notice] = 'You are not validate for this action'
      #   redirect_to new_user_session_path
      # end
      return redirect_to root_path unless current_user.admin? || current_user.manager?
    end
  end
end

app/controllers/manager/clients_controller.rb
module Manager  
  class ClientsController < BaseController
    before_action :set_client, only: %i[show edit update destroy]

    def index
      @clients = Client.all
    end

    def show; end

    def new
      @client = Client.new
    end

    def edit; end

    def create
      @client = Client.new(client_params)

      if @client.save
        redirect_to [:manager, @client], notice: "Client was successfully created."
      else
        render :new
      end
    end

    def update
      if @client.update(client_params)
        redirect_to [:manager, @client], notice: "Client was successfully update"
      else
        render :edit
      end
    end

    def destroy
      if @client.destroy
        flash[:notice] = "This Client destroyed successfully"
        redirect_to [:manager, @client]
      else
        flash[:notice] = "This client could not be destroyed"
      end
    end

    private

      def set_client
        @client = Client.find(params[:id])
      end

      def client_params
        params.require(:client).permit(:name, :contact, :email, :address, :profession)
      end
  end
end

app/controllers/manager/comments_controller.rb
module Manager
  class CommentsController < BaseController
    before_action :set_client
    before_action :set_project

    def new; end

    def create
      @comment = @project.comments.new(comment_params)

      respond_to do |format|
        if @comment.save
          format.html { [:manager, @client, @project] }
          format.js 
        else
          format.html { render 'new' }
          format.js 
        end
      end
    end 

    def destroy
      @comment = Comment.find(params[:id])

      if @comment.destroy
        flash[:notice] = "This Comment destroyed successfully"
        redirect_to [:manager, @client, @project]
      else
         flash[:notice] = "This Comment could not be destroyed"
      end
    end

    private

    def set_client
      @client = Client.find(params[:client_id])
    end

    def set_project
      @project = @client.projects.find(params[:project_id])
    end

    def comment_params
      permitted_params = params.require(:comment).permit(:content) 
      permitted_params[:client_id] = @client.id

      permitted_params
    end
  end 
end

app/controllers/manager/payments_controller.rb
module Manager
	class PaymentsController < BaseController

		def new
			@payment = Payment.new
			@clients = Client.order(:created_at)
		end

		def create
			@payment = Payment.new(payments_params)

	    if @payment.save
	    	# flash[:notice] = "sdafgasdg"
	      redirect_to root_path
	    else
	      render :new
	    end
		end

		private

		def payments_params 
			params.require(:payment).permit(:payment, :client_id, :project_id)
		end
	end
end

app/controllers/manager/projects_controller.rb
 module Manager
  class ProjectsController < BaseController
    before_action :set_client
    before_action :set_project, only: %i[show edit update destroy]
    
    def index
      @projects = @client.projects.order("created_at ASC")
    end
   
    def show; end  

    def new 
      @project = Project.new
    end 

    def create
      @project = @client.projects.new(project_params)

      if @project.save
        redirect_to [:manager, @client, @project], notice: "Project was successfully created."
      else
        render :new
      end
    end

    def edit; end

    def update
      if @project.update(project_params)
        redirect_to [:manager, @client, @project], notice: "Project was successfully created."
      else
        render :edit
      end
    end

    def destroy
      if @project.destroy
        flash[:notice] = "This project destroyed successfully"
        redirect_to [:manager, @client, @project]
      else
        flash[:notice] = "This Project could not be destroyed"
      end
    end

    private 

    def set_client
      @client = Client.find(params[:client_id])
    end

    def set_project
      @project = @client.projects.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :documentation, :project_cost, :time_tracking, :image)
    end
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/manager/clients/_form.html.erb
<div class="container">
  <%= form_for [:manager, @client] do |f| %>

    <% if @client.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>
        <% @client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Name", required: true  %>
    </div>

    <div class="field">
      <%= f.label :contact %>
      <%= f.number_field :contact, class: "form-control", placeholder: "Add you contact Number", required: true %>
    </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control", placeholder: "Email Id", required: true %>
    </div>

    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control", placeholder: "Address", required: true %>
    </div>

    <div class="field">
      <%= f.label :profession %>
      <%= f.text_area :profession, class: "form-control", placeholder: "e.g:Web developer, Application developer, Game developer", required: true %>
    </div><br>

    <div class="">
      <%= f.submit %>
    </div>
  <% end %>

  <%= link_to 'Back', manager_clients_path, class: "btn btn-warning btn-sm" %>
</div>

app/views/manager/clients/edit.html.erb
<div class="container">
  <h1>Editing Client</h1>

    <%= render 'form' %>
</div>

app/views/manager/clients/index.html.erb
<div class="container">

  <h1 class="text-center">Clients!</h1>

  <% if user_signed_in? && current_user %>
    <%= link_to 'New Client', new_manager_client_path, class: "btn btn-danger btn-sm" %>
  <% end %><br><br><hr>

  <table class="table table-responsive table-hover table-strips">
    <thead style= "background-color:#add8e6" >
      <tr>
        <th scope="row">Name</th>
        <th scope="row">Profession</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @clients.each do |client| %>
        <tr>
          <td><h5><%= client.name %></h5></td>
          <td><%= client.profession %></td>
          <td><%= link_to 'Show Client', [:manager, client], class: "btn btn-dark btn-sm" %></td>
          <td><%= link_to 'Projects', manager_client_projects_path(client, @project), class: "btn btn-secondary btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/manager/clients/new.html.erb
<div class="container">
  <h1 class="text-center"> Fill this form! </h1>
    <%= render 'form' %>
</div>

app/views/manager/clients/show.html.erb
<div class="container">
  <h3 class="text-center"><%= @client.name %></h3><br>

  <table class="table table-responsive table-hover">
    <tbody>

      <tr>
        <td><strong>Contact:</strong></td>
        <td><%= @client.contact %></td>
      </tr>

      <tr>
        <td><strong>Email:</strong></td>
        <td><%= @client.email %></td>
      </tr>

      <tr>
        <td><strong>Address:</strong></td>
        <td><%= @client.address %></td>
      </tr>

      <tr>
        <td><strong>Profession:</strong></td>
        <td><%= @client.profession %></td>
      </tr>

    </tbody>
  </table>

  <%= link_to 'Back', manager_clients_path(@manager), class: "btn btn-info btn-sm" %>
  
  <% if user_signed_in? && current_user %>
    <%= link_to 'Edit', edit_manager_client_path(@client), class: "btn btn-warning btn-sm" %> 
    <%= link_to 'Destroy', [:manager, @client], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary btn-sm" %>
  <% end %>
  
</div>