config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users, only: [:show]
     
  namespace :manager do
    resources :clients do 
      resources :projects do 
        resources :comments
      end
    end

    resources :payments
    
  end 

  namespace :admin do
    resources :users do
      member do 
        get :enable
        get :disable
      end
    end
  end


  root "manager/clients#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord

  has_many :projects
  has_many :comments
  has_many :payments

  validates :name, :address, :profession, presence: true
  validates :contact, presence: true, numericality: true
  validates :email, presence: true, format: { with: Devise.email_regexp, on: :create }, uniqueness: { case_sensitive: false }
  
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :project
  belongs_to :client

  validates :content, presence: true

end

app/models/payment.rb
class Payment < ApplicationRecord

  belongs_to :client
  belongs_to :project
  
end

app/models/project.rb
class Project < ApplicationRecord

	belongs_to :client

	has_many :comments, dependent: :destroy
	has_many :payments
	
	has_one_attached :image

	validates :name, presence: true
	validates :documentation, :time_tracking, presence: true
	validates :project_cost, presence: true, numericality: true

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :contact, presence: true, numericality: { only_integer: true }
  validates :email, presence: true, format: { with: Devise.email_regexp, on: :create }, uniqueness: { case_sensitive: false }


  ROLES= {
    admin: 'admin',
    manager: 'manager',
    member: 'member'
  }

  enum roles: ROLES

  def active_for_authentication?
    super and self.active?
  end

end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    before_action :restrict_non_admin

    def restrict_non_admin
      return redirect_to root_path unless current_user.admin? 
    end
  end
end
  

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    before_action :set_user, only: %i[show edit update destroy disable]

    def index
      @users = User.all
    end

    def show; end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to [:admin, @user], notice: "User was successfully created."
      else
        render :new
      end
    end

    def edit; end

    def update 
      if @user.update(user_params)
        redirect_to [:admin, @user], notice: "User was successfully created."
      else
        render :edit
      end
    end

    def destroy 
      if @user.destroy
        flash[:notice] = "This user destroyed successfully"
        redirect_to admin_users_path
      else
        flash[:notice] = "This user could not be destroyed"
      end
    end

    def disable
      if @user.active?
        @user.update(active: false)
        redirect_to admin_users_path 
      else
        @user.update(active: true)
        redirect_to admin_users_path 
      end
    end

    private 

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :contact, :password, :password_confirmation, :roles)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
	before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name last_name contact password password_confirmation])
  end

end

app/controllers/manager/base_controller.rb
module Manager
  class BaseController < ApplicationController
    before_action :validate_admin_or_manager

    def validate_admin_or_manager

      # if !(current_user.admin? || current_user.manager?)
      #   flash[:notice] = 'You are not validate for this action'
      #   redirect_to new_user_session_path
      # end
      return redirect_to root_path unless current_user.admin? || current_user.manager?
    end
  end
end

app/controllers/manager/clients_controller.rb
module Manager  
  class ClientsController < BaseController
    before_action :set_client, only: %i[show edit update destroy]

    def index
      @clients = Client.all
    end

    def show; end

    def new
      @client = Client.new
    end

    def edit; end

    def create
      @client = Client.new(client_params)

      if @client.save
        redirect_to [:manager, @client], notice: "Client was successfully created."
      else
        render :new
      end
    end

    def update
      if @client.update(client_params)
        redirect_to [:manager, @client], notice: "Client was successfully update"
      else
        render :edit
      end
    end

    def destroy
      if @client.destroy
        flash[:notice] = "This Client destroyed successfully"
        redirect_to [:manager, @client]
      else
        flash[:notice] = "This client could not be destroyed"
      end
    end

    private

      def set_client
        @client = Client.find(params[:id])
      end

      def client_params
        params.require(:client).permit(:name, :contact, :email, :address, :profession)
      end
  end
end

app/controllers/manager/projects_controller.rb
 module Manager
  class ProjectsController < BaseController
    before_action :set_client
    before_action :set_project, only: %i[show edit update destroy]
    
    def index
      @projects = @client.projects.order("created_at ASC")
    end
   
    def show; end  

    def new 
      @project = Project.new
    end 

    def create
      @project = @client.projects.new(project_params)

      if @project.save
        redirect_to [:manager, @client, @project], notice: "Project was successfully created."
      else
        render :new
      end
    end

    def edit; end

    def update
      if @project.update(project_params)
        redirect_to [:manager, @client, @project], notice: "Project was successfully created."
      else
        render :edit
      end
    end

    def destroy
      if @project.destroy
        flash[:notice] = "This project destroyed successfully"
        redirect_to [:manager, @client, @project]
      else
        flash[:notice] = "This Project could not be destroyed"
      end
    end

    private 

    def set_client
      @client = Client.find(params[:client_id])
    end

    def set_project
      @project = @client.projects.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :documentation, :project_cost, :time_tracking, :image)
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def create
    super
  end

  def after_sign_in_path_for(resource)
    # byebug
    if current_user.admin? || current_user.manager?
      admin_users_path(current_user)
    else
      user_path(current_user)
    end
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]

  def show
    @user = User.find(params[:id])
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to [:admin, @user], notice: 'User was successfully created.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :contact, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/projects/_form.html.erb
<div class="container">

	<%= form_for [:admin, @project] do |f| %>
		<% if @project.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@project.errors.count, "error") %> Fill this Credential First!</h2>
	      <ul>
	      <% @project.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
  <% end %>
	<br>

	<div class="field" >
		<%= f.label :name %>
		<%= f.text_field :name, placeholder: " Name", class: "form-control", required: true %>
	</div>
	<br>

	<div class="field" >
		<%= f.label :description %>
		<%= f.text_area :documentation, placeholder: "Description", class: "form-control", required: true %>
	</div>
	<br>

	<div class="field" >
		<%= f.label :project_cost %>
		<%= f.number_field :project_cost, placeholder: "9999$", class: "form-control", required: true %>
	</div>
	<br>

	<div class="field" >
		<%= f.label :time_tracking %>
		<%= f.text_field :time_tracking, placeholder: "", class: "form-control", required: true %>
	</div>
	<br>

	<div class="field" >
		<% if @project.image.attached? %>
			<%= image_tag @project.image, style: "width: 200px; display: block", required: true  %>
		<% end %>

		<%= f.label :image %>
		<%= f.file_field :image, class: "form-control" %>
	</div>
	<br>

	<div class="container">
		<%= f.submit class: "btn btn-outline-info" %>
	</div>
</div>

<% end %>

app/views/admin/projects/show.html.erb
<br>
<div class="container">

		<% if current_user %>
		<%= link_to 'Edit', edit_admin_project_path, class: "btn btn-danger" %>
		<%= link_to 'Delete', [:admin, @project], method: :delete, data: { confirm: 'Are you sure to delete project?' }, class: "btn btn-warning" %> 
		<% end %>
		<%= link_to 'Back', root_path, class: "btn btn-info" %>

	<table class="table table-responsive table-hover">
		<tbody>

			<tr>
				<% if @project.image.attached? %>
					<td><%= image_tag @project.image, style: "width: 200px; display: block" %></td>
				<% end %>
			</tr>

			<tr>
		  	<td><strong>Name:</strong></td>
		  	<td><%= @project.name %></td>
		  </tr>

			<tr>
				<td><strong>Description:</strong></td>
				<td><%= @project.documentation %></td>
			</tr>

			<tr>
				<td><strong>Project Cost:</strInfoong></td>
				<td><%= @project.project_cost%></td>
			</tr>

			<tr>
				<td><strong>Time Tracking:</strong></td>
				<td><%= @project.time_tracking %></td>
			</tr>

		</tbody>
	</table>

	<div id = "comment-content">
		<hr>
		
			<% @project.comments.each do |comment| %>
					<%= render 'admin/comments/comment', comment: comment %>
			<% end %>

		<%= render 'admin/comments/form' %>
	</div>
</div> 

app/views/projects/index.html.erb
<br>
<div class="container">

	<h1 class="text-center">Project Management Software!</h1>
	<br>

	<% if user_signed_in?%>
	<%= link_to 'New Project', new_project_path, class: "btn btn-danger index" %>
	<%= link_to 'Users', users_path, class: "btn btn-info index" %>
	<% end %>

	<table class="table table-responsive table-hover">
		<thead>
			<tr>
				<th scope="row">Name </th>
				<th scope="row">Description</th>
				<th scope="row">Project Cost </th>
				<th scope="row">Time Tracking </th>
				<th scope="row"> </th>
			</tr>
		</thead>
		<tbody>
			<% @projects.each do |project| %>
			  <tr>
		      <td><%= project.name %></td>
		      <td><%= project.documentation %></td>
		      <td><%= project.project_cost %></td>
		      <td><%= project.time_tracking %></td>
					<td><%= link_to 'Show Project', project_path(project), class: "btn btn-warning" %></td>
		    </tr>
			<% end %>
		</tbody>
	</table>
</div>
 