config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users, only: [:show]
     
  namespace :manager do
    resources :clients do 
      resources :projects do 
        resources :comments
      end
    end

    resources :payments
    
  end 

  namespace :admin do
    resources :users do
      member do 
        get :enable
        get :disable
      end
    end
  end


  root "manager/clients#index"

end

app/models/project.rb
class Project < ApplicationRecord

	belongs_to :client

	has_many :comments, dependent: :destroy
	has_many :payments
	
	has_one_attached :image

	validates :name, presence: true
	validates :documentation, :time_tracking, presence: true
	validates :project_cost, presence: true, numericality: true

end

app/controllers/manager/base_controller.rb
module Manager
  class BaseController < ApplicationController
    before_action :validate_admin_or_manager

    def validate_admin_or_manager

      # if !(current_user.admin? || current_user.manager?)
      #   flash[:notice] = 'You are not validate for this action'
      #   redirect_to new_user_session_path
      # end
      return redirect_to root_path unless current_user.admin? || current_user.manager?
    end
  end
end

app/controllers/manager/clients_controller.rb
module Manager  
  class ClientsController < BaseController
    before_action :set_client, only: %i[show edit update destroy]

    def index
      @clients = Client.all
    end

    def show; end

    def new
      @client = Client.new
    end

    def edit; end

    def create
      @client = Client.new(client_params)

      if @client.save
        redirect_to [:manager, @client], notice: "Client was successfully created."
      else
        render :new
      end
    end

    def update
      if @client.update(client_params)
        redirect_to [:manager, @client], notice: "Client was successfully update"
      else
        render :edit
      end
    end

    def destroy
      if @client.destroy
        flash[:notice] = "This Client destroyed successfully"
        redirect_to [:manager, @client]
      else
        flash[:notice] = "This client could not be destroyed"
      end
    end

    private

      def set_client
        @client = Client.find(params[:id])
      end

      def client_params
        params.require(:client).permit(:name, :contact, :email, :address, :profession)
      end
  end
end

app/controllers/manager/comments_controller.rb
module Manager
  class CommentsController < BaseController
    before_action :set_client
    before_action :set_project

    def new; end

    def create
      @comment = @project.comments.new(comment_params)

      respond_to do |format|
        if @comment.save
          format.html { [:manager, @client, @project] }
          format.js 
        else
          format.html { render 'new' }
          format.js 
        end
      end
    end 

    def destroy
      @comment = Comment.find(params[:id])

      if @comment.destroy
        flash[:notice] = "This Comment destroyed successfully"
        redirect_to [:manager, @client, @project]
      else
         flash[:notice] = "This Comment could not be destroyed"
      end
    end

    private

    def set_client
      @client = Client.find(params[:client_id])
    end

    def set_project
      @project = @client.projects.find(params[:project_id])
    end

    def comment_params
      permitted_params = params.require(:comment).permit(:content) 
      permitted_params[:client_id] = @client.id

      permitted_params
    end
  end 
end

app/controllers/manager/payments_controller.rb
module Manager
	class PaymentsController < BaseController

		def new
			@payment = Payment.new
			@clients = Client.order(:created_at)
		end

		def create
			@payment = Payment.new(payments_params)

	    if @payment.save
	    	# flash[:notice] = "sdafgasdg"
	      redirect_to root_path
	    else
	      render :new
	    end
		end

		private

		def payments_params 
			params.require(:payment).permit(:payment, :client_id, :project_id)
		end
	end
end

app/controllers/manager/projects_controller.rb
 module Manager
  class ProjectsController < BaseController
    before_action :set_client
    before_action :set_project, only: %i[show edit update destroy]
    
    def index
      @projects = @client.projects.order("created_at ASC")
    end
   
    def show; end  

    def new 
      @project = Project.new
    end 

    def create
      @project = @client.projects.new(project_params)

      if @project.save
        redirect_to [:manager, @client, @project], notice: "Project was successfully created."
      else
        render :new
      end
    end

    def edit; end

    def update
      if @project.update(project_params)
        redirect_to [:manager, @client, @project], notice: "Project was successfully created."
      else
        render :edit
      end
    end

    def destroy
      if @project.destroy
        flash[:notice] = "This project destroyed successfully"
        redirect_to [:manager, @client, @project]
      else
        flash[:notice] = "This Project could not be destroyed"
      end
    end

    private 

    def set_client
      @client = Client.find(params[:client_id])
    end

    def set_project
      @project = @client.projects.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :documentation, :project_cost, :time_tracking, :image)
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/manager/projects/_form.html.erb
<div class="container">

	<%= form_for [:manager, @client, @project] do |f| %>
		<% if @project.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@project.errors.count, "error") %> Fill this Credential First!</h2>
	      <ul>
	      <% @project.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
  <% end %>
	<br>

	<div class="field" >
		<%= f.label :name %>
		<%= f.text_field :name, placeholder: " Name", class: "form-control", required: true %>
	</div>
	<br>

	<div class="field" >
		<%= f.label :description %>
		<%= f.text_area :documentation, placeholder: "Description", class: "form-control", required: true %>
	</div>
	<br>

	<div class="field" >
		<%= f.label :project_cost %>
		<%= f.number_field :project_cost, placeholder: "9999$", class: "form-control", required: true %>
	</div>
	<br>

	<div class="field" >
		<%= f.label :time_tracking %>
		<%= f.text_field :time_tracking, placeholder: "", class: "form-control", required: true %>
	</div>
	<br>

	<div class="field" >
		<% if @project.image.attached? %>
			<%= image_tag @project.image, style: "width: 200px; display: block", required: true  %>
		<% end %>

		<%= f.label :image %>
		<%= f.file_field :image, class: "form-control" %>
	</div>
	<br>

	<div class="container">
		<%= f.submit class: "btn btn-outline-info btn-sm" %>
	</div>
</div>

<% end %>

app/views/manager/projects/edit.html.erb
<div class="container">
	<h3 class="text-center"> Edit Project! </h3>
		<%= link_to 'Back', manager_client_projects_path(@client, @project), class: "btn btn-outline-success btn-sm" %>
		<%= render 'form' %> 
</div>

app/views/manager/projects/index.html.erb
<br>
<div class="container">

  <h1 class="text-center">Project Management Software!</h1>
  <br>

  <%= link_to 'Back', manager_clients_path(@manager, @client, @project), class: "btn btn-dark btn-sm" %>
  <% if user_signed_in? && current_user %>
  <%= link_to 'New Project', new_manager_client_project_path(@client, @projects), class: "btn btn-success index btn-sm" %>
  <% end %><br><br><hr>

  <table class="table table-responsive table-hover">
    <thead style= "background-color:#add8e6">
      <tr>
        <th scope="row">Name </th>
        <th scope="row">Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
      <tr>
        <td><h5><%= project.name %></h5></td>
        <td><%= project.documentation %></td>
        <% if @client.projects.present? && user_signed_in? && current_user %>
          <td><%= link_to 'Edit', edit_manager_client_project_path(@client, project), class: "btn btn-warning btn-sm" %></td>
          <td><%= link_to 'Delete', [:manager, @client, project], method: :delete, data: { confirm: 'Are you sure to delete project?' }, class: "btn btn-danger btn-sm" %></td>
        <% end %>
        <td><%= link_to 'Show Project', manager_client_project_path(@client, project), class: "btn btn-primary btn-sm" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
 

app/views/manager/projects/new.html.erb
<br>
<div class="container">
	<h2 class="text-center"> New page </h2>

	<%= render 'form' %>
	
</div>

app/views/manager/projects/show.html.erb
<br>
<div class="container">
 
		<%= link_to 'Back', manager_client_projects_path(@project), class: "btn btn-dark btn-sm" %>
		<%= link_to 'Add Payment', new_manager_payment_path, class: "btn btn-dark btn-sm" %>

	<table class="table table-responsive table-hover">
		<tbody>

			<tr>
				<% if @project.image.attached? %>
					<td><%= image_tag @project.image, style: "width: 200px; display: block" %></td>
				<% end %>
			</tr>

			<tr>
		  	<td><strong>Name:</strong></td>
		  	<td><%= @project.name %></td>
		  </tr>

			<tr>
				<td><strong>Description:</strong></td>
				<td><%= @project.documentation %></td>
			</tr>

			<tr>
				<td><strong>Project Cost:</strInfoong></td>
				<td><%= @project.project_cost%></td>
			</tr>

			<tr>
				<td><strong>Time Tracking:</strong></td>
				<td><%= @project.time_tracking %></td>
			</tr>

			<tr>
				<td><strong>Payments:</strong></td>
				<td><%= @project.time_tracking %></td>
			</tr>

		</tbody>
	</table>

	<div>
		
	</div>

	<div id = "comment-content">
		<hr>
		
			<% @project.comments.each do |comment| %>
					<%= render 'manager/comments/comment', comment: comment %>
			<% end %>

		<%= render 'manager/comments/form' %>
	</div>
</div> 