config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :users, only: [:show]
     
  namespace :manager do
    resources :clients do 
      resources :projects do 
        resources :comments
      end
    end

    resources :payments
    
  end 

  namespace :admin do
    resources :users do
      member do 
        get :enable
        get :disable
      end
    end
  end


  root "manager/clients#index"

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :contact, presence: true, numericality: { only_integer: true }
  validates :email, presence: true, format: { with: Devise.email_regexp, on: :create }, uniqueness: { case_sensitive: false }


  ROLES= {
    admin: 'admin',
    manager: 'manager',
    member: 'member'
  }

  enum roles: ROLES

  def active_for_authentication?
    super and self.active?
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    before_action :set_user, only: %i[show edit update destroy disable]

    def index
      @users = User.all
    end

    def show; end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)

      if @user.save
        redirect_to [:admin, @user], notice: "User was successfully created."
      else
        render :new
      end
    end

    def edit; end

    def update 
      if @user.update(user_params)
        redirect_to [:admin, @user], notice: "User was successfully created."
      else
        render :edit
      end
    end

    def destroy 
      if @user.destroy
        flash[:notice] = "This user destroyed successfully"
        redirect_to admin_users_path
      else
        flash[:notice] = "This user could not be destroyed"
      end
    end

    def disable
      if @user.active?
        @user.update(active: false)
        redirect_to admin_users_path 
      else
        @user.update(active: true)
        redirect_to admin_users_path 
      end
    end

    private 

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :contact, :password, :password_confirmation, :roles)
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
 
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def create
    super
  end

  def after_sign_in_path_for(resource)
    # byebug
    if current_user.admin? || current_user.manager?
      admin_users_path(current_user)
    else
      user_path(current_user)
    end
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]

  def show
    @user = User.find(params[:id])
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to [:admin, @user], notice: 'User was successfully created.'
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :contact, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="container">

  <%= form_for [:admin, @user] do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> Fill this Credential First!</h2>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <br>

    <div class="field" >
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: " Name", class: "form-control", required: true %>
    </div>
    <br>

    <div class="field" >
      <%= f.label :email %>
      <%= f.text_field :email, placeholder: "Email", class: "form-control", required: true %>
    </div>
    <br>

    <div class="field" >
      <%= f.label :contact %>
      <%= f.number_field :contact, placeholder: "XXX-XXX-XXX", class: "form-control", required: true %>
    </div>
    <br>

    <div class="field">
      <%= f.label :roles %>
      <%= f.select :roles, [['Admin', "admin"], ['Manger', "manager"], ['Member', "member"]] %>
    </div>
    <br>

    <div class="field" >
      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "******", class: "form-control", required: true %>
    </div>
    <br>

    <div class="field" >
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, placeholder: "******", class: "form-control", required: true %>
    </div>
    <br>

      <div class="container">
      <%= f.submit class: "btn btn-secondary" %>
      </div>

  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container">

	<%= render 'form' %>
	
</div>

app/views/admin/users/index.html.erb
<br>
<div class="container">
  <h1 class="text-center">"All Users"</h1>

  <% if user_signed_in? %>
      <%= link_to 'New User', new_admin_user_path, class: "btn btn-warning" %>
  <% end %><br><br>

  <table class="table table-responsive table-hover">
    <thead style= "background-color:#add8e6">
        <tr>
          <th scope="row"> Name </th>
          <th scope="row"> Email </th>
          <th scope="row"> Contact </th>
          <th scope="row"> Status </th>
          <th colspan="3"></th>
        </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.contact %></td>
        <td><%= user.roles %></td>
        <td><%= link_to 'Show User', admin_user_path(user), class: "btn btn-dark btn-sm" %></td>
        <% if user.active? %>
          <td><%= link_to 'Disable', disable_admin_user_path(user), class: 'btn btn-primary btn-sm' %></td>
        <% else %>
          <td><%= link_to 'Enable', disable_admin_user_path(user), class: 'btn btn-info btn-sm' %></td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
 

app/views/admin/users/new.html.erb
<div class="container">
	<%= render 'form' %>
</div>

app/views/admin/users/show.html.erb
<br>
<div class="container">
  <table class="table table-responsive table-hover">
    <tbody>

      <tr>
        <td><strong>Name:</strong></td>
        <td><%= @user.name %></td>
      </tr>

      <tr>
        <td><strong>Contact:</strong></td>
        <td><%= @user.contact %></td>
      </tr>

      <tr>
        <td><strong>Email:</strInfoong></td>
        <td><%= @user.email%></td>
      </tr>

      <tr>
        <% if @user.present? && current_user && current_user.admin? %>
        <%= link_to 'Edit', edit_admin_user_path, class: "btn btn-danger" %>
        <%= link_to 'Delete', [:admin, @user], method: :delete, data: { confirm: 'Are you sure to delete this User?' }, class: "btn btn-warning" %> 
        <% end %>
        <%= link_to 'Back', admin_users_path, class: "btn btn-info" %> 
      </tr>
    </tbody>
  </table>
</div>